'use strict';
const assert=require('node:assert/strict'),D=require('../family-v2.js'),C=require('../community-domain-2.3.js'),M=require('../messages-2.2.js'),G=require('../spend-guard-2.2.1.js');
let count=0;const test=(name,fn)=>{fn();count++;console.log('PASS '+name);};
const base=(s,a,p)=>G.stamp(M.decorate(s,D.execute(s,a,p),a,p));
const run=(s,a,p)=>C.run(D,base,s,a,p);
const initial=()=>D.createState();
const house=(s=initial())=>run(s,'householdSettings',{enabled:true,limit:3000,perPayment:2000,members:['m1']});
const hp=(extra={})=>Object.assign({amount:500,memberId:'m1',category:'produce',merchant:'بقالة الحي',operationKey:D.uid()},extra);
const gp=(extra={})=>Object.assign({amount:1000,recipient:'صديق تجريبي',occasion:'rafd',color:'gold',note:'ألف مبروك، فرحتك فرحتنا',operationKey:D.uid()},extra);
test('Default parent and spouse fields are not assumed',()=>assert.deepEqual(C.relationOptions(C.model(D,initial())),{other:'فرد آخر',son:'ابني',daughter:'ابنتي',sibling:'أخ / أخت'}));
test('Settings are additive and preserve existing people, funds and goals',()=>{const s=initial(),n=run(s,'communitySettings',{showMother:true,showFather:false,married:true});assert.deepEqual(n.members,s.members);assert.equal(n.wallet,s.wallet);assert.deepEqual(n.goals,s.goals);assert(C.relationOptions(n.community).mother);assert(C.relationOptions(n.community).wife);assert(!C.relationOptions(n.community).father);assert(!s.community);});
test('Adding a spouse requires the user to enable married status',()=>assert.throws(()=>run(initial(),'communityMember',{name:'زوجتي',role:'adult',color:'pink',limit:1000,period:'daily',perPayment:1000,allowed:['grocery'],relationship:'wife'})));
test('Adding an optional mother preserves no-debit member setup',()=>{let s=run(initial(),'communitySettings',{showMother:true});s=run(s,'communityMember',{name:'والدتي',role:'adult',color:'pink',limit:1000,period:'daily',perPayment:1000,allowed:['grocery'],relationship:'mother'});assert.equal(s.wallet,125000);assert.equal(s.members.length,4);assert.equal(s.community.relations[s.members[3].id],'mother');});
test('Adult relation cannot be registered as a child',()=>{const s=run(initial(),'communitySettings',{showFather:true});assert.throws(()=>run(s,'communityMember',{name:'والدي',role:'child',relationship:'father'}));});
test('Disabling parent choices never deletes existing records',()=>{const s=run(initial(),'communitySettings',{showMother:true});s.community.relations.m1='mother';const n=run(s,'communitySettings',{});assert.equal(n.community.relations.m1,'mother');assert.equal(n.members.length,3);});
test('Configuring the daily house cap does not reserve or debit money',()=>{const s=house();assert.equal(s.wallet,125000);assert.equal(s.tx.length,0);});
test('House purchase is single debit and does not change personal allowance or gifts',()=>{const s=house(),p=hp(),n=run(s,'householdPay',p);assert.equal(n.wallet,124500);assert.equal(n.community.house.spent,500);assert.deepEqual(n.members,s.members);assert.equal(n.tx[0].memberId,'m1');assert.equal(n.tx[0].receipt.householdLeft,2500);assert.equal(n.tx[0].receipt.payer,'الأم');assert.equal(n.tx[0].receipt.allowanceLeft,null);assert.equal(n.tx[0].receipt.walletAfter,124500);assert.equal(s.wallet,125000);});
test('Owner may pay from the shared household cap',()=>assert.equal(run(house(),'householdPay',hp({memberId:''})).tx[0].memberId,''));
test('Unauthorized member cannot use house allowance',()=>assert.throws(()=>run(house(),'householdPay',hp({memberId:'m2'}))));
test('Children cannot receive household delegation in this release',()=>assert.throws(()=>run(initial(),'householdSettings',{enabled:true,limit:3000,perPayment:1000,members:['m2']})));
test('Paused delegate cannot pay',()=>{const s=house();s.members[0].active=false;assert.throws(()=>run(s,'householdPay',hp()));});
test('House category validation rejects unrelated spending',()=>assert.throws(()=>run(house(),'householdPay',hp({category:'cash'}))));
test('Per-purchase household cap enforced',()=>assert.throws(()=>run(house(),'householdPay',hp({amount:2001}))));
test('Shared daily cap applies across different payers',()=>{let s=run(house(),'householdPay',hp({amount:2000}));assert.throws(()=>run(s,'householdPay',hp({amount:1001,memberId:''})));});
test('Shared wallet funds must cover the house purchase',()=>{const s=house();s.wallet=100;assert.throws(()=>run(s,'householdPay',hp()));});
test('Duplicate household operation cannot debit twice',()=>{const p=hp(),s=run(house(),'householdPay',p);assert.throws(()=>run(s,'householdPay',p));assert.equal(s.wallet,124500);});
test('House disable and re-enable cannot erase spending',()=>{const s=run(house(),'householdPay',hp());let n=run(s,'householdSettings',{enabled:false,limit:3000,perPayment:2000,members:['m1']});assert.equal(n.community.house.spent,500);assert.throws(()=>run(n,'householdPay',hp()));n=run(n,'householdSettings',{enabled:true,limit:3000,perPayment:2000,members:['m1']});assert.equal(n.community.house.spent,500);});
test('House limit cannot be lowered below already spent money',()=>assert.throws(()=>run(run(house(),'householdPay',hp()),'householdSettings',{enabled:true,limit:400,perPayment:400,members:[]})));
test('Next Yemen day renews house cap only, not prior receipts',()=>{const s=run(house(),'householdPay',hp());s.community.house.key='2000-01-01';const n=run(s,'householdPay',hp());assert.equal(n.community.house.spent,500);assert.equal(n.tx[1].receipt.householdLeft,2500);});
test('House receipt is immutable after further purchase',()=>{const a=run(house(),'householdPay',hp()),r=JSON.stringify(a.tx[0].receipt),b=run(a,'householdPay',hp({amount:800}));assert.equal(JSON.stringify(b.tx[1].receipt),r);assert.equal(b.tx[0].receipt.householdLeft,1700);});
test('Gift and rafd perform one outward simulated debit, not an Eid hold',()=>{const s=initial(),n=run(s,'socialGift',gp());assert.equal(n.wallet,124000);assert.deepEqual(n.gifts,s.gifts);assert.deepEqual(n.members,s.members);assert.equal(n.tx[0].kind,'rafd');assert.equal(n.tx[0].receipt.type,'رفد عرس');assert.equal(n.tx[0].social.color,'gold');assert.equal(D.assets(n),D.assets(s)-1000);});
test('Duplicate gift is rejected',()=>{const p=gp(),s=run(initial(),'socialGift',p);assert.throws(()=>run(s,'socialGift',p));});
test('Gift monthly cap checks both gifts and rafd',()=>{let s=run(initial(),'socialLimit',{amount:1500});s=run(s,'socialGift',gp({occasion:'gift'}));assert.throws(()=>run(s,'socialGift',gp()));assert.equal(C.monthSpent(D,s),1000);});
test('Gift spending cap excludes old Eid and household expenses',()=>{let s=run(initial(),'gift',{memberIds:['m1'],amount:2000,note:'عيد مبارك',color:'gold'});s=house(s);s=run(s,'householdPay',hp());assert.equal(C.monthSpent(D,s),0);});
test('Gift cap cannot be reduced below month spending',()=>assert.throws(()=>run(run(initial(),'socialGift',gp()),'socialLimit',{amount:500})));
test('Month changes renew gift spending without mutating old transactions',()=>{const s=run(initial(),'socialGift',gp());s.tx[0].at=Date.UTC(2000,0,1);assert.equal(C.monthSpent(D,s),0);});
test('Unsupported occasion or color is rejected',()=>{assert.throws(()=>run(initial(),'socialGift',gp({occasion:'stock'})));assert.throws(()=>run(initial(),'socialGift',gp({color:'red'})));});
test('Whole-rial validation still rejects fractions, zero and negative amounts',()=>{for(const n of [0,-1,1.5,NaN])assert.throws(()=>run(initial(),'socialGift',gp({amount:n})));});
test('Legacy base actions preserve optional community settings',()=>{const s=house(),n=run(s,'familyPay',{memberId:'m2',amount:500,category:'food',merchant:'مقصف'});assert.equal(n.community.house.spent,0);assert.equal(n.members[1].spent,500);});
test('House transaction is visible to its member but not another member',()=>{const s=run(house(),'householdPay',hp());assert.equal(M.rows(s,'m1').length,1);assert.equal(M.rows(s,'m2').length,0);assert.equal(M.rows(s,'owner','family').length,1);});
test('Existing Eid open/cancel double-debit guards still work',()=>{let s=run(initial(),'gift',{memberIds:['m2'],amount:1000,note:'عيد مبارك',color:'blue'}),g=s.gifts[0];s=run(s,'openGift',{id:g.id});assert.equal(s.wallet,124000);assert.equal(s.members[1].giftBalance,1000);assert.throws(()=>run(s,'openGift',{id:g.id}));assert.throws(()=>run(s,'cancelGift',{id:g.id}));});
console.log(count+' community/domain checks passed');
